# Form implementation generated from reading ui file '.\Qt\ui\chatPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from input import Ui_Form as InputCell
from output import Ui_Form as OutputCell
import chat

class Ui_Form(object):
    is_ollama_answer = True
    chat_instance = chat.get_default_chat_instance()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setGeometry(QtCore.QRect(20, 20, 960, 500))
        self.scrollArea.setWidgetResizable(True)

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.chatroom_layout = QtWidgets.QVBoxLayout()
        self.chatroom_layout.setAlignment(Qt.AlignmentFlag.AlignTop)
        self.scrollAreaWidgetContents.setLayout(self.chatroom_layout)

        self.input_box = QtWidgets.QWidget(parent=Form)
        self.input_box.setObjectName("inputBox")
        self.input_box.setStyleSheet("""#inputBox {background-color: white;
                                     border-radius: 10px;  /* 圓角 */}""")
        self.input_box.setGeometry(QtCore.QRect(100, 540, 800, 150))
        self.input_box_layout = QtWidgets.QHBoxLayout()
        self.input_box.setLayout(self.input_box_layout)

        self.text_edit = QtWidgets.QTextEdit(parent=self.input_box)
        self.input_box_layout.addWidget(self.text_edit)
        self.text_edit.textChanged.connect(
            lambda: self.on_textEdit_textChanged())

        self.send_button = QtWidgets.QPushButton(parent=self.input_box)
        self.send_button.setEnabled(False)
        self.send_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Qt/icons/send.svg"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send_button.setIcon(icon)
        self.input_box_layout.addWidget(self.send_button)
        self.send_button.clicked.connect(lambda: self.on_pushButton_clicked())

        QtCore.QMetaObject.connectSlotsByName(Form)

    def on_textEdit_textChanged(self):
        question = self.text_edit.toPlainText()
        self.send_button.setEnabled(
            bool(question.strip()) and self.is_ollama_answer)

    def on_pushButton_clicked(self):
        question = self.text_edit.toPlainText()
        self.text_edit.setText("")
        self.add_user_input_to_chatroom(question)
        self.is_ollama_answer = False
        answer = self.chat_instance.ask(question)
        self.add_ollama_output_to_chatroom(answer)
        self.is_ollama_answer = True
        self.on_textEdit_textChanged()

    def add_user_input_to_chatroom(self, question):
        input_cell = InputCell()
        widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        input_cell.setupUi(widget)
        input_cell.label_2.setText(question)
        self.chatroom_layout.addWidget(widget)

    def add_ollama_output_to_chatroom(self, answer):
        output_cell = OutputCell()
        widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        output_cell.setupUi(widget)
        output_cell.label_2.setText(answer)
        self.chatroom_layout.addWidget(widget)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
