# Form implementation generated from reading ui file '.\Qt\ui\homePage.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)

        self.title = QtWidgets.QLabel(parent=Form)
        self.title.setText(
            "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600; color:#aaaaff;\">員工訓練與知識管理平台</span></p></body></html>")
        self.title.setMaximumHeight(100)
        self.title.setStyleSheet("""
    background-color: white;
    border: 1px solid #aaaaff;
    border-radius: 10px;  /* 圓角 */
    padding: 10px;       /* 內邊距 */
""")

        self.courseButton = QtWidgets.QPushButton(
            "課程培訓", parent=Form)
        self.courseButton.setMaximumHeight(100)

        self.testingButton = QtWidgets.QPushButton(
            "進行測驗", parent=Form)
        self.testingButton.setMaximumHeight(100)

        self.questionButton = QtWidgets.QPushButton(
            "問卷調查", parent=Form)
        self.questionButton.setMaximumHeight(100)

        spacerItem = QtWidgets.QSpacerItem(20, 20)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.title)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.courseButton)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.testingButton)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.questionButton)
        self.verticalLayout.addItem(spacerItem)

        self.verticalLayout.setAlignment(Qt.AlignmentFlag.AlignHCenter)

        QtCore.QMetaObject.connectSlotsByName(Form)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
