# Form implementation generated from reading ui file '.\Qt\ui\input.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.hLayout = QtWidgets.QHBoxLayout(Form)
        self.hLayout.setAlignment(Qt.AlignmentFlag.AlignRight)

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setPixmap(QtGui.QPixmap("./Qt/icons/input.png"))
        self.label.setScaledContents(True)
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.hLayout.addWidget(self.label)

        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.hLayout.addWidget(self.label_2)

        QtCore.QMetaObject.connectSlotsByName(Form)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    ui.label_2.setText("HelloHelloHelloHelloHelloHelloHelloHello")
    Form.show()
    sys.exit(app.exec())
