# Form implementation generated from reading ui file '.\Qt\ui\output.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setObjectName("Form")
        self.hLayout = QtWidgets.QHBoxLayout(Form)
        self.hLayout.setAlignment(Qt.AlignmentFlag.AlignLeft)

        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setPixmap(QtGui.QPixmap("./Qt/icons/llama.png"))
        self.label.setScaledContents(True)
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.hLayout.addWidget(self.label)

        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.hLayout.addWidget(self.label_2)

        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Qt/icons/thumb_up.svg"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.hLayout.addWidget(self.pushButton)

        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Qt/icons/thumb_down.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.hLayout.addWidget(self.pushButton_2)

        QtCore.QMetaObject.connectSlotsByName(Form)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    ui.label_2.setText("TestTestTEst")
    Form.show()
    sys.exit(app.exec())
